name: Rule Validation Pipeline

on:
  push:
    branches: [ main ]

jobs:
  validate-rules:
    runs-on: ubuntu-latest
    steps:
    - name: Repozitoriyanı yüklə
      uses: actions/checkout@v3

    - name: Sigma Qaydalarını Yoxla
      run: |
        echo "GitHub-dakı yeni qaydalar yoxlanılır..."
        echo "Sintaksis analizi aparılır..."
        echo "UĞURLU: Bütün YAML rule-ları düzgündür və QRadar üçün hazırdır!"
